import re

from flask import Blueprint, request


def create_ui_baseline_blueprint():
    blueprint = Blueprint("ui_baseline", __name__)

    @blueprint.after_app_request
    def apply_ui_baseline(response):
        if response.status_code != 200 or response.mimetype != "text/html":
            return response
        html = response.get_data(as_text=True)
        if "</head>" not in html or "</body>" not in html or "data-weld-ui-v2" in html:
            return response

        path = request.path
        progress = re.fullmatch(r"(?:/weld)?/projects/(\d+)/progress", path)
        entry = re.fullmatch(r"(?:/weld)?/projects/(\d+)/entry", path)
        thumbs = re.fullmatch(r"(?:/weld)?/projects/(\d+)/thumbnails", path)
        progress_list = re.fullmatch(r"(?:/weld)?/projects/(\d+)/progress-list", path)
        favorites = re.fullmatch(r"(?:/weld)?/favorites", path)
        projects = re.fullmatch(r"(?:/weld)?/projects-screen", path)
        if not any((progress, entry, thumbs, progress_list, favorites, projects)):
            return response

        viewer_mode = bool(progress and request.args.get("viewer") == "1")
        if progress:
            html = html.replace("longEdge=320&format=jpeg", "longEdge=500&format=jpeg")
            old = "progressMap.set(key(active),data);draw();dialog.close();"
            new = (
                "const uiKeepLeft=viewer.scrollLeft,uiKeepTop=viewer.scrollTop;"
                "progressMap.set(key(active),data);draw();"
                "requestAnimationFrame(()=>{viewer.scrollLeft=uiKeepLeft;viewer.scrollTop=uiKeepTop});"
                "dialog.close();"
            )
            html = html.replace(old, new, 1)

        boot = "<script data-weld-ui-v2>document.documentElement.classList.add('ui-viewer-mode-v2')</script>" if viewer_mode else ""
        css = r"""
<style data-weld-ui-v2>
:root{--ui2-bar:#fff;--ui2-line:#e5e7eb;--ui2-blue:#1967d2;--ui2-muted:#6b7280;--ui2-bg:#f5f6f8;--ui2-h:54px;--ui2-touch:48px}
.ui2-appbar{display:none}
@media(max-width:820px){
 body{overscroll-behavior-y:none}
 .ui2-appbar{display:flex;position:sticky;top:0;z-index:100;min-height:var(--ui2-h);align-items:center;gap:4px;padding:3px max(6px,env(safe-area-inset-right)) 3px max(6px,env(safe-area-inset-left));background:rgba(255,255,255,.97);border-bottom:1px solid var(--ui2-line);backdrop-filter:saturate(180%) blur(12px)}
 .ui2-icon{width:var(--ui2-touch);height:var(--ui2-touch);min-width:var(--ui2-touch);min-height:var(--ui2-touch);padding:0;border:0;border-radius:12px;background:transparent;color:#202124;display:inline-flex;align-items:center;justify-content:center;font:inherit;font-size:1.2rem;font-weight:800;touch-action:manipulation;cursor:pointer}.ui2-icon:active{background:#f1f3f4}.ui2-back{color:var(--ui2-blue);font-size:2rem;font-weight:500}
 .ui2-title{min-width:0;flex:1;padding:0 4px}.ui2-title strong{display:block;font-size:1rem;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.ui2-title small{display:block;margin-top:2px;color:var(--ui2-muted);font-size:.7rem;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}
 .ui2-appbar details.more{display:block!important;position:relative!important;flex:0 0 auto!important}.ui2-appbar details.more>summary,.ui2-entry-more>summary{width:48px!important;height:48px!important;min-width:48px!important;min-height:48px!important;padding:0!important;border:0!important;background:transparent!important;border-radius:12px!important;display:flex!important;align-items:center!important;justify-content:center!important;font-size:1.25rem!important}.ui2-appbar .more-menu,.ui2-entry-more .more-menu{right:0!important;top:50px!important;width:min(255px,calc(100vw - 16px))!important;z-index:150!important;border-radius:13px!important;padding:6px!important;box-shadow:0 10px 32px #0003!important}.ui2-appbar .more-menu .button,.ui2-entry-more .more-menu .button{display:block!important;width:100%!important;min-height:46px!important;margin:1px 0!important;padding:0 12px!important;border:0!important;border-radius:9px!important;background:#fff!important;text-align:left!important;font-size:.95rem!important}
 body.ui2-progress main,body.ui2-entry main{padding:0!important;max-width:none!important}body.ui2-progress main>.top,body.ui2-entry main>.top{display:none!important}body.ui2-progress .card,body.ui2-entry .card{border-left:0!important;border-right:0!important;border-radius:0!important}
 body.ui2-progress .toolbar{position:sticky!important;top:var(--ui2-h)!important;z-index:80!important;display:flex!important;flex-wrap:wrap!important;justify-content:space-between!important;align-items:center!important;gap:4px 8px!important;height:auto!important;min-height:50px!important;padding:4px max(6px,env(safe-area-inset-right))!important;background:#fff!important;border-bottom:1px solid var(--ui2-line)!important;white-space:normal!important}
 body.ui2-progress .toolbar>.spacer,body.ui2-progress .toolbar>.desktop-tools,body.ui2-progress .toolbar>.compact-rotate,body.ui2-progress .toolbar>.compact-fullscreen,body.ui2-progress .toolbar>.more{display:none!important}.ui2-pages,.ui2-drawing{display:flex;align-items:center;gap:2px;flex:0 0 auto}.ui2-pages .nav-button{width:44px!important;min-width:44px!important;min-height:44px!important;padding:0!important;border:0!important;background:transparent!important;font-size:1.45rem!important}.ui2-pages .page-field{gap:2px!important}.ui2-pages .page-field>span:first-child{display:none!important}.ui2-pages .page-field input{width:44px!important;min-height:38px!important;padding:0 3px!important;border:0!important;border-radius:10px!important;background:#f3f4f6!important;font-weight:800!important}.ui2-pages .page-total{font-size:.78rem!important;color:var(--ui2-muted)!important}
 .ui2-drawing>.button,.ui2-drawing>a.button{display:inline-flex!important;align-items:center!important;justify-content:center!important;width:44px!important;min-width:44px!important;min-height:44px!important;padding:0!important;border:0!important;border-radius:10px!important;background:transparent!important;text-decoration:none!important;font-size:1.15rem!important}.ui2-drawing>.page-favorite-view{font-size:1.45rem!important}body.ui2-progress .statusline{display:none!important}
 body.ui2-entry .controls{position:sticky!important;top:var(--ui2-h)!important;z-index:80!important;margin:0!important;padding:5px max(6px,env(safe-area-inset-right))!important;background:#fff!important;border-bottom:1px solid var(--ui2-line)!important;display:flex!important;align-items:center!important;gap:4px!important;flex-wrap:wrap!important}body.ui2-entry .controls label{display:flex!important;align-items:center!important;gap:3px!important;font-size:0!important}body.ui2-entry .controls label::before{content:'P';font-size:.85rem;font-weight:800;color:var(--ui2-muted)}body.ui2-entry #page{width:46px!important;min-height:40px!important;border:0!important;border-radius:10px!important;background:#f3f4f6!important;padding:0 4px!important;text-align:center!important;font-weight:800!important}
 body.ui2-entry #prev,body.ui2-entry #next,body.ui2-entry #rotate,body.ui2-entry .page-favorite-view,body.ui2-entry [data-thumbnail-grid-launch]{min-width:44px!important;width:44px!important;min-height:44px!important;padding:0!important;border:0!important;background:transparent!important;font-size:0!important;border-radius:10px!important}body.ui2-entry #prev::before{content:'‹';font-size:1.45rem}body.ui2-entry #next::before{content:'›';font-size:1.45rem}body.ui2-entry #rotate::before{content:'↻';font-size:1.2rem}body.ui2-entry [data-thumbnail-grid-launch]::before{content:'▦';font-size:1.15rem}body.ui2-entry #ocr{margin-left:auto!important}body.ui2-entry #ocr,body.ui2-entry #save{min-height:42px!important;padding:0 10px!important}body.ui2-entry #reset,body.ui2-entry #bulkDelete,body.ui2-entry [data-go-favorites]{display:none!important}
 body.ui2-grid main,body.ui2-favorites main,body.ui2-list main{padding-top:0!important}body.ui2-grid .top,body.ui2-favorites .top{display:none!important}body.ui2-grid .toolbar,body.ui2-favorites .toolbar{position:sticky!important;top:var(--ui2-h)!important;z-index:80!important;margin:0 0 9px!important;border:0!important;border-bottom:1px solid var(--ui2-line)!important;border-radius:0!important;background:rgba(255,255,255,.98)!important;padding:6px max(8px,env(safe-area-inset-right))!important;box-shadow:0 1px 2px #0000000d!important}body.ui2-favorites .toolbar{flex-wrap:wrap!important}.ui2-cols{display:flex;gap:4px;margin-left:auto}.ui2-cols button{width:40px;height:38px;border:1px solid #bdc1c6;border-radius:9px;background:#fff;font-weight:800}.ui2-cols button.active{border-color:var(--ui2-blue);background:#e8f0fe;color:#174ea6}
 body.ui2-list .topbar{position:sticky!important;top:0!important;z-index:100!important;height:var(--ui2-h)!important;margin:0 -8px 8px!important;padding:3px max(6px,env(safe-area-inset-right))!important;background:#fff!important;border-bottom:1px solid var(--ui2-line)!important}body.ui2-list .back{width:48px!important;min-width:48px!important;height:48px!important;min-height:48px!important;padding:0!important;border:0!important;background:transparent!important;font-size:0!important;color:var(--ui2-blue)!important}body.ui2-list .back::before{content:'‹';font-size:2rem;font-weight:500}body.ui2-list .filters{top:var(--ui2-h)!important}
 body.ui2-projects main{padding-top:0!important}.ui2-root{position:sticky;top:0;z-index:100;margin:0 -16px 16px!important;padding:6px max(10px,env(safe-area-inset-right))!important;min-height:62px;display:flex!important;flex-direction:row!important;align-items:center!important;gap:8px!important;background:rgba(255,255,255,.97)!important;border-bottom:1px solid var(--ui2-line)!important}.ui2-root>div:first-child{min-width:0;flex:1}.ui2-root h1{font-size:1.15rem!important}.ui2-root-actions{display:flex!important;gap:4px!important;flex-wrap:nowrap!important}.ui2-root-actions button{width:48px!important;min-width:48px!important;height:48px!important;min-height:48px!important;padding:0!important;border-radius:12px!important;font-size:0!important}.ui2-root-actions [data-ui2-favorites]::before{content:'★';font-size:1.35rem;color:#f9ab00}.ui2-root-actions #new-project::before{content:'＋';font-size:1.5rem;color:#fff}.ui2-root-actions #new-project{background:var(--ui2-blue)!important;border-color:var(--ui2-blue)!important}
}
@media(max-width:360px) and (orientation:portrait){body.ui2-progress .toolbar{justify-content:center!important}.ui2-pages{flex:1 1 100%;justify-content:center}.ui2-drawing{flex:1 1 100%;justify-content:center;gap:8px}.ui2-title small{display:none}}
html.ui-viewer-mode-v2,html.ui-viewer-mode-v2 body{margin:0!important;width:100%!important;height:100%!important;min-height:100%!important;background:#e9eaed!important;overflow:hidden!important}html.ui-viewer-mode-v2 main{margin:0!important;padding:0!important;max-width:none!important;width:100%!important;height:100dvh!important;min-height:100dvh!important}html.ui-viewer-mode-v2 .top,html.ui-viewer-mode-v2 .toolbar,html.ui-viewer-mode-v2 .statusline,html.ui-viewer-mode-v2 .summary,html.ui-viewer-mode-v2 .progress-thumbs,html.ui-viewer-mode-v2 .ui2-appbar{display:none!important}html.ui-viewer-mode-v2 .card{margin:0!important;padding:0!important;border:0!important;border-radius:0!important;width:100%!important;height:100dvh!important;min-height:100dvh!important;overflow:hidden!important}html.ui-viewer-mode-v2 .viewer{display:block!important;width:100%!important;height:100dvh!important;min-height:100dvh!important;max-height:none!important;overflow:auto!important}.ui2-viewer-controls{display:none}html.ui-viewer-mode-v2 .ui2-viewer-controls{display:flex;position:absolute;z-index:160;top:max(8px,env(safe-area-inset-top));right:max(8px,env(safe-area-inset-right));gap:8px}html.ui-viewer-mode-v2 .ui2-viewer-controls button{width:48px;height:48px;border:0;border-radius:24px;background:rgba(32,33,36,.78);color:#fff;font-size:1.35rem;font-weight:800}
</style>
"""

        if progress:
            project_id = progress.group(1)
            script = f"""
<script data-weld-ui-v2>
(() => {{const projectId={project_id},viewerMode={str(viewer_mode).lower()};const isIOS=/iPad|iPhone|iPod/.test(navigator.userAgent)||(navigator.platform==='MacIntel'&&navigator.maxTouchPoints>1);const toolbar=document.querySelector('.toolbar'),top=document.querySelector('.top'),back=document.getElementById('back'),prev=document.getElementById('prev'),next=document.getElementById('next'),pageField=toolbar?.querySelector('.page-field'),more=document.getElementById('moreMenu'),full=document.getElementById('fullscreenCompact'),canvas=document.getElementById('canvas'),viewer=document.getElementById('viewer'),rotate=document.getElementById('rotateCompact'),zoomIn=document.getElementById('zoomIn'),zoomReset=document.getElementById('zoomReset');if(!toolbar||!back||!prev||!next||!pageField||!viewer||!canvas)return;const page=()=>Math.max(1,Number(document.getElementById('page')?.value)||1);
if(viewerMode){{const c=document.createElement('div');c.className='ui2-viewer-controls';const r=document.createElement('button');r.type='button';r.textContent='↻';r.setAttribute('aria-label','90度回転');const x=document.createElement('button');x.type='button';x.textContent='×';x.setAttribute('aria-label','図面集中表示を終了');c.append(r,x);document.body.append(c);x.onclick=()=>location.href=`/weld/projects/${{projectId}}/progress?page=${{page()}}`;let fitting=false,fitted=false;const fit=()=>{{if(fitting||canvas.hidden||!canvas.width||!viewer.clientHeight||!zoomIn||!zoomReset)return;fitting=true;zoomReset.click();requestAnimationFrame(()=>{{let g=0;while(canvas.getBoundingClientRect().height<viewer.clientHeight-1&&g<8){{const before=canvas.getBoundingClientRect().height;zoomIn.click();g++;if(canvas.getBoundingClientRect().height<=before+.5)break}}viewer.scrollLeft=Math.max(0,(viewer.scrollWidth-viewer.clientWidth)/2);viewer.scrollTop=Math.max(0,(viewer.scrollHeight-viewer.clientHeight)/2);fitted=true;fitting=false}})}};r.onclick=()=>{{rotate?.click();requestAnimationFrame(()=>requestAnimationFrame(fit))}};const mo=new MutationObserver(()=>{{if(!fitted&&canvas.width&&!canvas.hidden){{requestAnimationFrame(()=>requestAnimationFrame(fit));mo.disconnect()}}}});mo.observe(canvas,{{attributes:true,attributeFilter:['width','height','hidden']}});setTimeout(fit,80);return}}
document.body.classList.add('ui2-progress');const app=document.createElement('div');app.className='ui2-appbar';const b=document.createElement('button');b.type='button';b.className='ui2-icon ui2-back';b.textContent='‹';b.setAttribute('aria-label','戻る');b.onclick=()=>{{try{{const u=new URL(document.referrer);if(u.origin===location.origin&&u.pathname.startsWith('/weld/')){{history.back();return}}}}catch(_e){{}}back.click()}};const title=document.createElement('div');title.className='ui2-title';title.innerHTML='<strong>進捗入力</strong><small></small>';title.querySelector('small').textContent=top?.querySelector('.meta')?.textContent?.trim()||'';if(full){{full.className='ui2-icon';full.textContent='⛶';full.setAttribute('aria-label','図面集中表示');if(isIOS)full.onclick=e=>{{e.preventDefault();e.stopPropagation();location.href=`/weld/projects/${{projectId}}/progress?page=${{page()}}&viewer=1`}}}}app.append(b,title);if(full)app.append(full);if(more)app.append(more);toolbar.parentNode.insertBefore(app,toolbar);const pages=document.createElement('div');pages.className='ui2-pages';pages.append(prev,pageField,next);toolbar.prepend(pages);const actions=document.createElement('div');actions.className='ui2-drawing';toolbar.append(actions);const move=()=>{{for(const el of [document.querySelector('.page-favorite-view'),document.getElementById('rotateCompact'),toolbar.querySelector('[aria-label="ページ一覧"]'),toolbar.querySelector('[aria-label="進捗一覧"]')])if(el&&el.parentNode!==actions)actions.append(el)}};const obs=new MutationObserver(move);obs.observe(toolbar,{{childList:true,subtree:true}});move();setTimeout(move,100);setTimeout(move,350);document.addEventListener('pointerdown',e=>{{if(more?.open&&!more.contains(e.target))more.removeAttribute('open')}},true);document.addEventListener('keydown',e=>{{if(e.key==='Escape'&&more?.open)more.removeAttribute('open')}}) }})();
</script>
"""
        elif entry:
            script = r"""
<script data-weld-ui-v2>
(()=>{document.body.classList.add('ui2-entry');const top=document.querySelector('.top'),controls=document.querySelector('.controls'),back=document.getElementById('back');if(!top||!controls||!back)return;const app=document.createElement('div');app.className='ui2-appbar';const b=document.createElement('button');b.type='button';b.className='ui2-icon ui2-back';b.textContent='‹';b.setAttribute('aria-label','戻る');b.onclick=()=>{try{const u=new URL(document.referrer);if(u.origin===location.origin&&u.pathname.startsWith('/weld/')){history.back();return}}catch(_e){}back.click()};const title=document.createElement('div');title.className='ui2-title';title.innerHTML='<strong>図面エントリー</strong><small></small>';title.querySelector('small').textContent=top.querySelector('.meta')?.textContent?.trim()||'';const more=document.createElement('details');more.className='more ui2-entry-more';more.innerHTML='<summary class="ui2-icon" aria-label="その他の操作">⋯</summary><div class="more-menu"></div>';const menu=more.querySelector('.more-menu');app.append(b,title,more);controls.parentNode.insertBefore(app,controls);const collect=()=>{for(const id of ['reset','bulkDelete']){const el=document.getElementById(id);if(el&&el.parentNode!==menu){el.classList.add('button');menu.append(el)}}const fav=controls.querySelector('[data-go-favorites]');if(fav&&fav.parentNode!==menu){fav.textContent='★ お気に入りページ一覧';fav.classList.add('button');menu.append(fav)}};const mo=new MutationObserver(collect);mo.observe(controls,{childList:true,subtree:true});collect();setTimeout(collect,100);setTimeout(collect,350);document.addEventListener('pointerdown',e=>{if(more.open&&!more.contains(e.target))more.removeAttribute('open')},true)})();
</script>
"""
        elif thumbs:
            script = r"""
<script data-weld-ui-v2>(()=>{document.body.classList.add('ui2-grid');const top=document.querySelector('.top'),back=document.getElementById('back');if(!top||!back)return;const app=document.createElement('div');app.className='ui2-appbar';const b=document.createElement('button');b.type='button';b.className='ui2-icon ui2-back';b.textContent='‹';b.setAttribute('aria-label','戻る');b.onclick=()=>back.click();const title=document.createElement('div');title.className='ui2-title';title.innerHTML='<strong>ページ一覧</strong><small></small>';title.querySelector('small').textContent=top.querySelector('.meta')?.textContent?.trim()||'';app.append(b,title);document.querySelector('main').prepend(app)})();</script>
"""
        elif favorites:
            script = r"""
<script data-weld-ui-v2>(()=>{document.body.classList.add('ui2-favorites');const top=document.querySelector('.top'),back=document.getElementById('back'),toolbar=document.querySelector('.toolbar'),grid=document.getElementById('grid'),search=document.getElementById('search');if(!top||!back||!toolbar||!grid)return;const app=document.createElement('div');app.className='ui2-appbar';const b=document.createElement('button');b.type='button';b.className='ui2-icon ui2-back';b.textContent='‹';b.setAttribute('aria-label','工事一覧へ戻る');b.onclick=()=>back.click();const title=document.createElement('div');title.className='ui2-title';title.innerHTML='<strong>お気に入り</strong><small>工事横断</small>';app.append(b,title);document.querySelector('main').prepend(app);const key='weldFavoriteGridCols';let cols=matchMedia('(max-width:640px)').matches?2:3;try{const n=Number(localStorage.getItem(key));if([1,2,3,4].includes(n))cols=n}catch(_e){}const wrap=document.createElement('div');wrap.className='ui2-cols';for(const n of [1,2,3,4]){const x=document.createElement('button');x.type='button';x.textContent=String(n);x.title=`${n}列`;x.onclick=()=>apply(n);wrap.append(x)}toolbar.append(wrap);function apply(n){cols=n;grid.style.gridTemplateColumns=`repeat(${n},minmax(0,1fr))`;[...wrap.children].forEach((x,i)=>x.classList.toggle('active',i+1===n));try{localStorage.setItem(key,String(n))}catch(_e){}}apply(cols)})();</script>
"""
        elif progress_list:
            script = r"""
<script data-weld-ui-v2>(()=>{document.body.classList.add('ui2-list')})();</script>
"""
        else:
            script = r"""
<script data-weld-ui-v2>(()=>{document.body.classList.add('ui2-projects');const header=document.querySelector('.header'),newButton=document.getElementById('new-project');if(!header||!newButton)return;header.classList.add('ui2-root');const existingWrap=newButton.parentElement;existingWrap.classList.add('ui2-root-actions');const fav=[...existingWrap.querySelectorAll('button')].find(x=>x!==newButton&&/お気に入り/.test(x.textContent||''));if(fav){fav.dataset.ui2Favorites='1';fav.title='お気に入りページ一覧'}})();</script>
"""
        html = html.replace("</head>", boot + css + "</head>", 1)
        html = html.replace("</body>", script + "</body>", 1)
        response.set_data(html)
        return response

    return blueprint
